### ISSUE TITLE
Jellyseerr write into container

### ISSUE THREAD

**Issue by hfabio** [rapejim/jellyfin-plexdrive-docker#5]
Is there any way to insert in the `docker-compose.yml` a volume between the containers to make Jellyseerr write content in Jellyfin through plex-drive?

like, using this `docker-compose.yml`
```yml
version: '3.5'
services:
  jellyfin:
    container_name: jellyfin
    image: rapejim/jellyfin-plexdrive-docker:arm64 #running over raspberry pi 4b
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /docker/jellyfin/config:/config
    environment:
      TZ: America/Bahia
      PUID: '1000'
      PGID: '1000'
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: host
    environment:
        LOG_LEVEL: debug
        TZ: America/Bahia
    volumes:
        - /path/to/appdata/config:/app/config #what to do here? Maybe /docker/jellyseerr/config ???
    restart: unless-stopped
```

is it possible to pipe the download from jellyseerr into google drive through plexdrive in jellyfin container?
